[package]
name = "npy"
version = "0.1.0"
authors = ["Pavel Potocek <pavelpotocek@gmail.com>"]

[dependencies]
byteorder = "*"
rustc-serialize = "*"
nom = "*"
serde = "*"
serde_derive = "*"
memmap = "*"
npy-derive = { path = "npy-derive" }
# serde_json = "*"
